[package]
name = "sound-mimic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
hound = "3.5.1"
image = { version = "0.24.7", default-features = false, features = ["qoi"] }
rustfft = "6.1.0"
wt = { package = "wasmtime", version = "14.0.4" }
