[package]
name = "sound-mimic"
version = "0.1.0"
edition = "2021"

[features]
profile = []

[dependencies]
anyhow = "1.0.79"
argh = "0.1.12"
hound = "3.5.1"
image = "0.24.7"
nalgebra = { version = "0.32.3", features = ["rayon"] }
ordered-float = "4.2.0"
rayon = "1.8.0"
fft = { package = "rustfft", version = "6.1.0" }
tracing = "0.1.40"
tracing-timing = "0.6.0"
wt = { package = "wasmtime", version = "16.0.0" }

[target.'cfg(target_os = "macos")'.dependencies]
apple-accelerate = { git = "https://github.com/zetanumbers/apple-accelerate.git" }

[profile.release]
# lto = true
debug = true
