[package]
name = "mimic-interactive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy_egui = "0.31"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
